---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ocp4-examples
  namespace: openshift-gitops
spec:
  description: Deploy ocp4-examples
  sourceRepos:
    - https://github.com/rdiazgav/demo-kustomize.git
  destinations:
    - namespace: appargo* # frontend
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
