apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops-operator
bases:
  - base
patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-gitops-operator
      namespace: openshift-gitops-operator
    path: patch-channel.yaml
