---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  annotations:
    openshift.io/display-name: Frontend 
    openshift.io/description: Frontend deployment
    openshift.io/requester: Kustomize
